# Generated by Django 3.2.6 on 2024-07-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPhospho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hugo_symbol', models.CharField(max_length=255)),
                ('swiss_prot_acc_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'masterphospho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDataExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('project_id', models.CharField(default=None, max_length=255, unique=True)),
                ('files', models.JSONField(default=dict)),
                ('uploaded_date', models.DateTimeField(auto_now=True, null=True)),
                ('extended_on', models.DateTimeField(null=True)),
                ('reason_for_extension', models.TextField(default=None, null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDataProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dna_mutation', models.CharField(default=None, max_length=255, null=True)),
                ('methylation', models.CharField(default=None, max_length=255, null=True)),
                ('rna', models.CharField(default=None, max_length=255, null=True)),
                ('proteome', models.CharField(default=None, max_length=255, null=True)),
                ('clinical_information', models.CharField(default=None, max_length=255, null=True)),
                ('cnv', models.CharField(default=None, max_length=255, null=True)),
                ('phospho', models.CharField(default=None, max_length=255, null=True)),
                ('fusion', models.CharField(default=None, max_length=255, null=True)),
                ('sql_path', models.CharField(blank=True, max_length=155)),
                ('is_clinical', models.BooleanField(blank=True, null=True)),
                ('available_steps', models.JSONField(default=dict)),
                ('viz_type', models.CharField(default=None, max_length=255)),
                ('uploaded_date', models.DateTimeField(auto_now=True, null=True)),
                ('project_id', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
