# Generated by Django 3.2.6 on 2024-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataprojects',
            name='error_found',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userdataprojects',
            name='project_status',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
