# Generated by Django 3.2.6 on 2024-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0002_auto_20241118_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataprojects',
            name='error_found',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdataprojects',
            name='project_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
