# Generated by Django 3.2.6 on 2024-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0003_auto_20241118_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataprojects',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
