# Generated by Django 3.2.6 on 2024-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0004_alter_userdataprojects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataprojects',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
