# Generated by Django 3.2.6 on 2024-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0005_alter_userdataprojects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataprojects',
            name='project_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
