# Generated by Django 3.2.6 on 2024-11-19 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0006_alter_userdataprojects_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataprojects',
            name='project_id',
            field=models.CharField(default=datetime.datetime(2024, 11, 19, 10, 54, 16, 245117, tzinfo=utc), max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
