# Generated by Django 3.2.6 on 2024-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0007_alter_userdataprojects_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataprojects',
            name='response',
            field=models.JSONField(default=dict),
        ),
    ]
