# Generated by Django 3.2.6 on 2024-12-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0008_userdataprojects_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdataprojects',
            name='error_found',
        ),
        migrations.RemoveField(
            model_name='userdataprojects',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='userdataprojects',
            name='response',
        ),
    ]
