DEFAULT_CONFIG = {
    "skin": "moono-lisa",
    "toolbar_Basic": [["Source", "-", "Bold", "Italic"]],
    "toolbar_Full": [
        [
            "Styles",
            "Format",
            "Bold",
            "Italic",
            "Underline",
            "Strike",
            "SpellChecker",
            "Undo",
            "Redo",
        ],
        ["Link", "Unlink", "Anchor"],
        ["Image", "Flash", "Table", "HorizontalRule"],
        ["TextColor", "BGColor"],
        ["Smiley", "SpecialChar"],
        ["Source"],
        ["html5video"],
    ],
    "toolbar": "Full",
    "height": 291,
    # "width": 835,
    "filebrowserWindowWidth": 940,
    "filebrowserWindowHeight": 725,
    "filebrowserBrowseUrl": "/k-corev/ckeditor/browse/all",
    "filebrowserImageBrowseUrl": "/k-corev/ckeditor/browse/image",
    "filebrowserVideoBrowseUrl": "/k-corev/ckeditor/browse/video",
    "filebrowserUploadUrl": "/k-corev/ckeditor/upload/",
}
