# Generated by Django 3.2.6 on 2023-10-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputGTF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('gtf_start', models.IntegerField(blank=True, null=True)),
                ('gtf_end', models.IntegerField(blank=True, null=True)),
                ('gene_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gtf_exon', models.CharField(blank=True, max_length=255, null=True)),
                ('rel_start', models.IntegerField(blank=True, null=True)),
                ('rel_end', models.IntegerField(blank=True, null=True)),
                ('gtf_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'output_gtf',
            },
        ),
    ]
