# Generated by Django 3.2.6 on 2023-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_outputgtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadvisualization',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
