# Generated by Django 3.2.6 on 2024-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_downloadvisualization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
