# Generated by Django 3.2.6 on 2024-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnamutation',
            old_name='dbsnp_rs',
            new_name='dbsnp_rs_dna',
        ),
        migrations.RenameField(
            model_name='downloadvisualization',
            old_name='project_id',
            new_name='project_id_app',
        ),
        migrations.RenameField(
            model_name='rniddetails',
            old_name='cnv',
            new_name='cnv_rnid',
        ),
        migrations.RenameField(
            model_name='rniddetails',
            old_name='dna_mutation',
            new_name='dna_mutation_rnid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_id_app',
        ),
        migrations.RemoveField(
            model_name='downloadvisualization',
            name='id',
        ),
        migrations.AddField(
            model_name='downloadvisualization',
            name='id_down',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cnv',
            name='chromosome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outputgtf',
            name='gene_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),

    ]
