# Generated by Django 3.2.6 on 2024-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240816_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnamutation',
            name='variant_classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rna',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
