# Generated by Django 3.2.6 on 2024-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240819_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnamutation',
            old_name='dbsnp_rs_dna',
            new_name='dbsnp_rs',
        ),
        migrations.RenameField(
            model_name='downloadvisualization',
            old_name='id_down',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='downloadvisualization',
            old_name='project_id_app',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='rniddetails',
            old_name='cnv_rnid',
            new_name='cnv',
        ),
        migrations.RenameField(
            model_name='rniddetails',
            old_name='dna_mutation_rnid',
            new_name='dna_mutation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id_app',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='dnamutation',
            name='dbsnp_rs',
            field=models.TextField(blank=True, db_column='dbsnp_rs_dna', null=True),
        ),
        migrations.AlterField(
            model_name='downloadvisualization',
            name='id',
            field=models.AutoField(db_column='id_down', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='downloadvisualization',
            name='project_id',
            field=models.IntegerField(blank=True, db_column='project_id_app', null=True),
        ),
        migrations.AlterField(
            model_name='rniddetails',
            name='cnv',
            field=models.BooleanField(blank=True, db_column='cnv_rnid', null=True),
        ),
        migrations.AlterField(
            model_name='rniddetails',
            name='dna_mutation',
            field=models.BooleanField(blank=True, db_column='dna_mutation_rnid', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_column='user_id_app', default='', max_length=200),
        ),
    ]
