# Generated by Django 3.2.6 on 2024-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clinicalinformation_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadvisualization',
            name='project_id',
            field=models.CharField(blank=True, db_column='project_id_app', max_length=255, null=True),
        ),
    ]
