# Generated by Django 3.2.6 on 2024-11-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_downloadvisualization_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalinformation',
            name='smoker',
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='smok_curr_yn',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='smok_yn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
