# Generated by Django 3.2.6 on 2024-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0002_userdataextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataextension',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
