# Generated by Django 3.2.6 on 2024-06-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0003_alter_userdataextension_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdataextension',
            old_name='available_steps',
            new_name='files',
        ),
    ]
