# Generated by Django 3.2.6 on 2024-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0004_rename_available_steps_userdataextension_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataextension',
            name='project_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
