# Generated by Django 3.2.6 on 2024-06-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0005_alter_userdataextension_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdataextension',
            old_name='user',
            new_name='username',
        ),
    ]
