# Generated by Django 3.2.6 on 2024-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data_visualization', '0006_rename_user_userdataextension_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataextension',
            name='files',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userdataprojects',
            name='available_steps',
            field=models.JSONField(default=dict),
        ),
    ]
